### ISSUE TITLE
Can NextJS trigger browser to hot reload after module update?

### ISSUE THREAD

**Issue by ivawzh** [maerzhase/webpack-clear-require-cache-plugin#1]
Hi, thanks a lot for sharing this super useful plugin.

While I enjoy using this plugin, I am still hitting refresh manually on the browser every time after code updates. Wondering if you have already solved this issue in a way?

Cheers =]

**Comment by maerzhase** [comment]
Hi there. Next-js has its own hot-module loading integrated. This is activated by default. The latest version even introduced their own "hot loading" called "fast refresh" which got us a huge performance boost and keeps the state although a component is "reloaded". 

This plugin only solves the case were server side modules get out of sync with the client-side modules and does so by clearing the node require cache (server-side) upon rebuilding. 

This is actually just relevant if you develop a shared module apart from the next-js `src` folder. 

Other than that i am not sure what your question or request is. Hope I could help you!
